In [1]:
import numpy as np
import pandas as pd
from scipy.stats import zscore

C:\Users\sreekar chidurala\Anaconda3\lib\site-packages\ipykernel\parentpoller.py:116: UserWarning: Parent poll failed.  If the frontend dies,
                the kernel may be left running.  Please let us know
                about your system (bitness, Python, etc.) at
                ipython-dev@scipy.org
  ipython-dev@scipy.org""")


In [2]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import accuracy_score

In [5]:
df=pd.read_csv("train.csv")

In [6]:
df.head()

number_of_elements  mean_atomic_mass  wtd_mean_atomic_mass  \
0                   4         88.944468             57.862692   
1                   5         92.729214             58.518416   
2                   4         88.944468             57.885242   
3                   4         88.944468             57.873967   
4                   4         88.944468             57.840143   

   gmean_atomic_mass  wtd_gmean_atomic_mass  entropy_atomic_mass  \
0          66.361592              36.116612             1.181795   
1          73.132787              36.396602             1.449309   
2          66.361592              36.122509             1.181795   
3          66.361592              36.119560             1.181795   
4          66.361592              36.110716             1.181795   

   wtd_entropy_atomic_mass  range_atomic_mass  wtd_range_atomic_mass  \
0                 1.062396          122.90607              31.794921   
1                 1.057755          122.90607              36.161939   
2                 0.975980          122.90607              35.741099   
3                 1.022291          122.90607              33.768010   
4                 1.129224          122.90607              27.848743   

   std_atomic_mass      ...        wtd_mean_Valence  gmean_Valence  \
0        51.968828      ...                2.257143       2.213364   
1        47.094633      ...                2.257143       1.888175   
2        51.968828      ...                2.271429       2.213364   
3        51.968828      ...                2.264286       2.213364   
4        51.968828      ...                2.242857       2.213364   

   wtd_gmean_Valence  entropy_Valence  wtd_entropy_Valence  range_Valence  \
0           2.219783         1.368922             1.066221              1   
1           2.210679         1.557113             1.047221              2   
2           2.232679         1.368922             1.029175              1   
3           2.226222         1.368922             1.048834              1   
4           2.206963         1.368922             1.096052              1   

   wtd_range_Valence  std_Valence  wtd_std_Valence  critical_temp  
0           1.085714     0.433013         0.437059           29.0  
1           1.128571     0.632456         0.468606           26.0  
2           1.114286     0.433013         0.444697           19.0  
3           1.100000     0.433013         0.440952           22.0  
4           1.057143     0.433013         0.428809           23.0  

[5 rows x 82 columns]

In [16]:
df_x= df.iloc[:,1:81]

In [11]:
#df_x.head()

In [20]:
df_y=df.iloc[:,81]
df_y.head()

0    29.0
1    26.0
2    19.0
3    22.0
4    23.0
Name: critical_temp, dtype: float64

In [21]:
z_data=df_x.apply(zscore)
z_data.head()

mean_atomic_mass  wtd_mean_atomic_mass  gmean_atomic_mass  \
0          0.046733             -0.451651          -0.158850   
1          0.174269             -0.432071           0.059368   
2          0.046733             -0.450978          -0.158850   
3          0.046733             -0.451314          -0.158850   
4          0.046733             -0.452324          -0.158850   

   wtd_gmean_atomic_mass  entropy_atomic_mass  wtd_entropy_atomic_mass  \
0              -0.611819             0.044358                -0.003707   
1              -0.604180             0.777430                -0.015267   
2              -0.611658             0.044358                -0.218984   
3              -0.611739             0.044358                -0.103615   
4              -0.611980             0.044358                 0.162775   

   range_atomic_mass  wtd_range_atomic_mass  std_atomic_mass  \
0           0.133725              -0.053039         0.378186   
1           0.133725               0.108900         0.134901   
2           0.133725               0.093294         0.378186   
3           0.133725               0.020128         0.378186   
4           0.133725              -0.199372         0.378186   

   wtd_std_atomic_mass       ...         mean_Valence  wtd_mean_Valence  \
0             0.609240       ...            -0.907755         -0.752156   
1             0.627122       ...            -1.147084         -0.752156   
2             0.610928       ...            -0.907755         -0.740164   
3             0.610084       ...            -0.907755         -0.746160   
4             0.607550       ...            -0.907755         -0.764149   

   gmean_Valence  wtd_gmean_Valence  entropy_Valence  wtd_entropy_Valence  \
0      -0.805912          -0.711705         0.186292             0.035183   
1      -1.116731          -0.719454         0.664971            -0.014779   
2      -0.805912          -0.700728         0.186292            -0.062235   
3      -0.805912          -0.706224         0.186292            -0.010538   
4      -0.805912          -0.722618         0.186292             0.113627   

   range_Valence  wtd_range_Valence  std_Valence  wtd_std_Valence  
0      -0.837959          -0.406166    -0.838372        -0.520070  
1      -0.033011          -0.362352    -0.426866        -0.450821  
2      -0.837959          -0.376957    -0.838372        -0.503304  
3      -0.837959          -0.391562    -0.838372        -0.511524  
4      -0.837959          -0.435376    -0.838372        -0.538178  

[5 rows x 80 columns]

In [24]:
from sklearn.decomposition import PCA
pca = PCA(n_components=80, svd_solver='full')

In [25]:
pca.fit(z_data)
print(pca.explained_variance_ratio_) 

[3.84706935e-01 1.05281725e-01 9.58056008e-02 7.97774589e-02
 5.95487920e-02 3.82154175e-02 3.65405497e-02 3.14461150e-02
 2.38387353e-02 1.99227219e-02 1.85110174e-02 1.47625326e-02
 1.19158748e-02 1.01084468e-02 9.89814021e-03 7.87721964e-03
 7.27770601e-03 5.45869804e-03 4.88350741e-03 3.84527467e-03
 2.91224958e-03 2.83273013e-03 2.59062836e-03 2.09529839e-03
 1.98098435e-03 1.87138844e-03 1.63759302e-03 1.44036167e-03
 1.27819037e-03 1.16374617e-03 1.03677387e-03 9.68704355e-04
 9.23515461e-04 7.26690286e-04 6.85359264e-04 6.14580351e-04
 5.73355360e-04 4.65423972e-04 4.30656122e-04 4.05101442e-04
 3.29259542e-04 3.06447052e-04 2.41915701e-04 2.26410659e-04
 2.23286194e-04 2.13843983e-04 1.93807266e-04 1.87035030e-04
 1.80248648e-04 1.65372907e-04 1.56664592e-04 1.31746481e-04
 1.24410607e-04 1.19371546e-04 1.07357612e-04 9.56692639e-05
 8.96944584e-05 8.20989233e-05 7.76570226e-05 7.25465535e-05
 5.77587565e-05 4.94107468e-05 4.46738194e-05 4.00485438e-05
 3.63127651e-05 3.260945

In [26]:
pca.explained_variance_ratio_.cumsum()

array([0.38470693, 0.48998866, 0.58579426, 0.66557172, 0.72512051,
       0.76333593, 0.79987648, 0.83132259, 0.85516133, 0.87508405,
       0.89359507, 0.9083576 , 0.92027347, 0.93038192, 0.94028006,
       0.94815728, 0.95543499, 0.96089369, 0.96577719, 0.96962247,
       0.97253472, 0.97536745, 0.97795808, 0.98005337, 0.98203436,
       0.98390575, 0.98554334, 0.9869837 , 0.98826189, 0.98942564,
       0.99046241, 0.99143112, 0.99235463, 0.99308132, 0.99376668,
       0.99438126, 0.99495462, 0.99542004, 0.9958507 , 0.9962558 ,
       0.99658506, 0.99689151, 0.99713342, 0.99735983, 0.99758312,
       0.99779696, 0.99799077, 0.9981778 , 0.99835805, 0.99852343,
       0.99868009, 0.99881184, 0.99893625, 0.99905562, 0.99916298,
       0.99925865, 0.99934834, 0.99943044, 0.9995081 , 0.99958064,
       0.9996384 , 0.99968781, 0.99973249, 0.99977253, 0.99980885,
       0.99984146, 0.99986995, 0.99989454, 0.99991551, 0.99993386,
       0.99995136, 0.99996763, 0.99997698, 0.9999847 , 0.99999

In [33]:
pca_data=pca.fit_transform(z_data)
pca_data


array([[-3.74338612e+00,  6.71759869e-01,  3.01073363e+00, ...,
        -2.20656609e-01, -3.96118692e-01,  2.00709639e-01],
       [-4.52100723e+00, -3.80770362e-01,  1.65884403e+00, ...,
         2.21044667e-01,  4.20903270e-01, -1.13906596e+00],
       [-3.56566468e+00,  7.31438688e-01,  3.10237014e+00, ...,
         7.91462329e-03, -5.05746907e-01,  1.62327922e-01],
       ...,
       [ 1.03770537e+01, -9.65676086e-01,  1.57343121e+00, ...,
         5.91913545e-02, -7.19095818e-01, -3.68826320e-01],
       [ 9.66384871e+00, -1.02065434e+00,  1.20468836e+00, ...,
        -1.61591760e+00,  1.46884525e-01, -6.65790072e-02],
       [ 3.83682174e+00,  1.54974238e+00, -1.86263347e+00, ...,
         3.02680894e-01,  1.64970074e-01,  1.04493533e-01]])

In [34]:
from sklearn.decomposition import PCA
pca = PCA(n_components=10)
principalComponents = pca.fit_transform(z_data)
principalComponents

array([[-3.74338612e+00,  6.71760847e-01,  3.01073337e+00, ...,
        -2.20709330e-01, -3.96025446e-01,  2.00876511e-01],
       [-4.52100723e+00, -3.80769996e-01,  1.65884362e+00, ...,
         2.21064787e-01,  4.20819610e-01, -1.13883206e+00],
       [-3.56566468e+00,  7.31439653e-01,  3.10236978e+00, ...,
         7.87586389e-03, -5.05659693e-01,  1.62521676e-01],
       ...,
       [ 1.03770537e+01, -9.65678056e-01,  1.57343300e+00, ...,
         5.92714289e-02, -7.19028572e-01, -3.69339236e-01],
       [ 9.66384871e+00, -1.02065662e+00,  1.20468999e+00, ...,
        -1.61581618e+00,  1.46881566e-01, -6.71236709e-02],
       [ 3.83682174e+00,  1.54974426e+00, -1.86263162e+00, ...,
         3.02520439e-01,  1.65289520e-01,  1.04779509e-01]])

In [ ]:
##regression

In [35]:
features=z_data


label = np.array(df["critical_temp"])

In [36]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, label, test_size=0.2, random_state=0)

In [52]:
y_train.shape

(17010,)

In [49]:
len(predicted_labels)

17010

In [39]:
from sklearn.tree import DecisionTreeRegressor

In [111]:
DTClassifier= DecisionTreeRegressor (max_depth=35, min_samples_split =2)
DTClassifier.fit(X_train,y_train)
predicted_labels = DTClassifier.predict(X_train)
predicted_labels 

array([ 3.4625    , 79.        , 14.73833333, ...,  3.97      ,
        1.53      , 85.55252326])

In [112]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_train,predicted_labels)

17.42845516109031

In [103]:
#for whole data
DTClassifier= DecisionTreeRegressor (max_depth=50, min_samples_split =2)
DTClassifier.fit(z_data,df_y)
predicted_labels = DTClassifier.predict(z_data)
predicted_labels 

array([24.43166667, 26.5       , 28.16666667, ...,  1.98      ,
        1.84      , 12.1       ])

In [104]:
from sklearn.metrics import mean_squared_error
mean_squared_error(df_y,predicted_labels)

18.514249538204826

In [ ]:
#using pca

In [96]:
from sklearn.decomposition import PCA
pca = PCA(n_components=20)
principalComponents = pca.fit_transform(z_data)
principalComponents

array([[-3.74338612e+00,  6.71760431e-01,  3.01073345e+00, ...,
        -2.27144204e-01, -1.41944551e-01, -3.27968128e-01],
       [-4.52100723e+00, -3.80770571e-01,  1.65884412e+00, ...,
        -4.46858833e-01,  3.94770304e-01, -4.07367524e-04],
       [-3.56566468e+00,  7.31439217e-01,  3.10236995e+00, ...,
        -1.41466271e-01, -1.21106286e-01, -3.46890200e-01],
       ...,
       [ 1.03770537e+01, -9.65676720e-01,  1.57343167e+00, ...,
        -5.96984879e-01, -2.63465342e-02,  9.47206360e-01],
       [ 9.66384871e+00, -1.02065521e+00,  1.20468889e+00, ...,
        -7.23367912e-01, -2.88075576e-02,  7.25213684e-01],
       [ 3.83682173e+00,  1.54974309e+00, -1.86263343e+00, ...,
         1.50642691e+00, -4.27098708e-01, -3.80936087e-01]])

In [80]:
principalDf = pd.DataFrame(data = principalComponents)
principalDf.head()


0         1         2         3         4         5         6   \
0 -3.743386  0.671760  3.010733  1.770929  0.241249 -0.242313  0.428352   
1 -4.521007 -0.380771  1.658844  1.144624  0.975353 -0.981376 -0.320455   
2 -3.565665  0.731439  3.102370  1.875407  0.290381 -0.247928  0.468570   
3 -3.659504  0.698511  3.052878  1.821137  0.265167 -0.246088  0.446728   
4 -3.889817  0.631144  2.942587  1.679454  0.195817 -0.230389  0.399022   

         7         8         9         10        11        12        13  \
0 -0.220679 -0.395998  0.200790  0.633411  0.158783 -0.505090 -0.036181   
1  0.221060  0.420852 -1.139054  1.067222  0.578253 -0.579870 -0.057677   
2  0.007896 -0.505633  0.162416  0.738795  0.150660 -0.551090 -0.037668   
3 -0.110198 -0.449642  0.180939  0.685178  0.155098 -0.527250 -0.036778   
4 -0.425539 -0.293523  0.242891  0.534095  0.164538 -0.464551 -0.035702   

         14        15        16        17        18        19  
0 -0.223467  0.720944  0.266148 -0.226966 -0.141101 -0.332153  
1 -0.798628  1.217910  0.997346 -0.447006  0.394843 -0.003290  
2 -0.253861  0.755675  0.309601 -0.141106 -0.120325 -0.351925  
3 -0.238122  0.738462  0.286243 -0.185587 -0.131760 -0.341257  
4 -0.196982  0.685442  0.232476 -0.302440 -0.155738 -0.316710

In [107]:
DTClassifier= DecisionTreeRegressor (max_depth=50, min_samples_split =2)
DTClassifier.fit(principalDf,df_y)
predicted_labels = DTClassifier.predict(principalDf)
predicted_labels 

array([24.43166667, 26.5       , 28.16666667, ...,  1.98      ,
        1.84      , 12.1       ])

In [108]:
from sklearn.metrics import mean_squared_error
mean_squared_error(df_y,predicted_labels)

18.514249538204826

In [113]:
#train test using pca


In [129]:
finalDf = pd.concat([principalDf,df["critical_temp"]],axis=1)


In [130]:
finalDf.head()

0         1         2         3         4         5         6  \
0 -3.743386  0.671760  3.010733  1.770929  0.241249 -0.242313  0.428352   
1 -4.521007 -0.380771  1.658844  1.144624  0.975353 -0.981376 -0.320455   
2 -3.565665  0.731439  3.102370  1.875407  0.290381 -0.247928  0.468570   
3 -3.659504  0.698511  3.052878  1.821137  0.265167 -0.246088  0.446728   
4 -3.889817  0.631144  2.942587  1.679454  0.195817 -0.230389  0.399022   

          7         8         9      ...              11        12        13  \
0 -0.220679 -0.395998  0.200790      ...        0.158783 -0.505090 -0.036181   
1  0.221060  0.420852 -1.139054      ...        0.578253 -0.579870 -0.057677   
2  0.007896 -0.505633  0.162416      ...        0.150660 -0.551090 -0.037668   
3 -0.110198 -0.449642  0.180939      ...        0.155098 -0.527250 -0.036778   
4 -0.425539 -0.293523  0.242891      ...        0.164538 -0.464551 -0.035702   

         14        15        16        17        18        19  critical_temp  
0 -0.223467  0.720944  0.266148 -0.226966 -0.141101 -0.332153           29.0  
1 -0.798628  1.217910  0.997346 -0.447006  0.394843 -0.003290           26.0  
2 -0.253861  0.755675  0.309601 -0.141106 -0.120325 -0.351925           19.0  
3 -0.238122  0.738462  0.286243 -0.185587 -0.131760 -0.341257           22.0  
4 -0.196982  0.685442  0.232476 -0.302440 -0.155738 -0.316710           23.0  

[5 rows x 21 columns]

In [141]:
features1=finalDf.iloc[:,0:20]


label1 = np.array(finalDf["critical_temp"])

In [167]:
from sklearn.model_selection import train_test_split

X_train1, X_test1, y_train1, y_test1 = train_test_split(features1,label1, test_size=0.2, random_state=1)

In [153]:

X_train1.shape

(17010, 20)

In [154]:
 X_test1.shape

(4253, 20)

In [157]:
y_train1.shape

(17010,)

In [156]:
y_test1.shape

(4253,)

In [183]:
DTClassifier= DecisionTreeRegressor (max_depth=50, min_samples_split =3,min_samples_leaf=5)
DTClassifier.fit(X_train1,y_train1)
predicted_labels = DTClassifier.predict(X_test1)


In [184]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test1,predicted_labels)

146.1665092642994